### ISSUE TITLE
希望能支持在vue中的style 的注释,现阶段只能适用于 template 字段

### ISSUE THREAD

**Issue by mxm646690173** [1714080902120/html-nest-comment#1]

**Comment by 1714080902120** [comment]
这个好说，不过最好是再写一个，因为命名上只是针对`html`，另外`vscode`插件写起来不难的，你可以看下我写的入门文章：https://zhuanlan.zhihu.com/p/635411894

**Comment by 1714080902120** [comment]
已经发布了，https://marketplace.visualstudio.com/items?itemName=1714080902120.css-nest-comment
